apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- eso.yaml

images:
  - name: nginx
    newTag: 1.0.0

configMapGenerator:
- name: some-configmap
  behavior: create
  envs:
  - config.env

# https://github.com/kubernetes-sigs/kustomize/tree/master/examples/transformerconfigs/crd
# configurations:
#   - kustomize_transforms.yaml

# https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/crds/
# Regardless of that, multiple issues are in Kustomize GitHub repository, essentially saying that does not work
# crds:
#   - crd_extr.yaml
