apiVersion: apps/v1
kind: Deployment
metadata:
  name: limited-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: limited-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: limited-deployment
    spec:
      containers:
        - name: nginx
          image: nginx:1.0.0
      nodeSelector:
        example.com/nodelabel1: "somevalue"