apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

namespace: namespaceA

images:
  - name: nginx
    newName: someregistryforA/nginx

configMapGenerator:
- name: some-configmap
  behavior: merge
  envs:
  - config.env