apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml

images:
  - name: nginx
    newTag: 1.0.0

configMapGenerator:
- name: some-configmap
  behavior: create
  envs:
  - config.env

secretGenerator:
- name: some-secret
  behavior: create
  envs:
  - super.secret.env