apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

namespace: namespaceA

namePrefix: a-

images:
  - name: nginx
    newName: someregistryforA/nginx

configMapGenerator:
- name: some-configmap
  behavior: merge
  envs:
  - config.env

patches:
- patch: |-
    apiVersion: external-secrets.io/v1beta1
    kind: SecretStore
    metadata:
      name: azurekeyvaultstore
    spec:
      provider:
        azurekv:
          vaultUrl: https://akvinthecloud.vault.azure.net